spring:
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 10
      database: 3
      password: 123321
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/