spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6611
      connect-timeout: 5000
      database: 3
      password: 123321
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/